name: Setup Azure Resources for Terraform Backend

on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Resources Location'
        required: true

jobs:
  setup-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create --name topicos-backend-group --location ${{github.event.inputs.location}}

      - name: Create Storage Account
        run: |
          az storage account create \
            --name topicosbackendaccount \
            --resource-group topicos-backend-group \
            --location ${{github.event.inputs.location}} \
            --sku Standard_LRS \
            --kind StorageV2

      - name: Create Blob Container
        run: |
          az storage container create \
            --name terraform-state \
            --account-name topicosbackendaccount
